### ISSUE TITLE
"Wayland" Linux build depends on libxkbcommon

### ISSUE THREAD

**Issue by nigels-com** [dcnieho/FreeGLUT#38]
```
cmake -G 'Unix Makefiles' -DFREEGLUT_WAYLAND=1
```

Building FreeGLUT with EGL support, I came across an undocumented package dependency, that appears to be specific to EGL:

```
[  4%] Building C object CMakeFiles/freeglut_static.dir/src/fg_ext.c.o
make[2]: *** [CMakeFiles/freeglut_static.dir/src/fg_callbacks.c.o] Error 1
In file included from /home/nigels/dev/FreeGLUT/freeglut/freeglut/src/fg_internal.h:200:0,
                 from /home/nigels/dev/FreeGLUT/freeglut/freeglut/src/fg_display.c:29:
/home/nigels/dev/FreeGLUT/freeglut/freeglut/src/wayland/fg_internal_wl.h:37:33: fatal error: xkbcommon/xkbcommon.h: No such file or directory
 #include <xkbcommon/xkbcommon.h>
                                 ^
compilation terminated.
```

Ought to be mentioned in documentation that libxkbcommon-dev is required. (Ubuntu 14.04 here)

Solution is:
```
 sudo apt-get install libxkbcommon-dev
```

**Comment by rcmaniac25** [comment]
Poking @tarnyko as they were the one to implement Wayland.

**Comment by Tarnyko** [comment]
Hi @rcmaniac25,

xkbcommon is required because Wayland, contrary to X11, does not have its own keyboard helper functions (even Weston, the reference Wayland compositor, pulls it).

As CMake does not really checks for dependencies, I guess you are referring to the "README" and "README.cmake" files ; agreedly, they need an update. Will prepare this and let you know on this thread.

**Comment by Tarnyko** [comment]
Here it is : https://github.com/dcnieho/FreeGLUT/pull/40 .
Please review or comment.

**Comment by rcmaniac25** [comment]
@nigels-com Does the pull request suit you?

**Comment by nigels-com** [comment]
Looks great!  Thanks!

- Nigel

**Comment by dcnieho** [comment]
cool, #40 looks good. Will merge that along with #39 when its ready (given the laborious number of steps to get it into svn as well and back again). Thanks!
