### ISSUE TITLE
warning: variable ‘menuID’ set but not used

### ISSUE THREAD

**Issue by 0-wiz-0** [dcnieho/FreeGLUT#54]
gcc warns:
````
freeglut/freeglut/progs/demos/CallbackMaker/CallbackMaker.c: In function ‘main’:
freeglut/freeglut/progs/demos/CallbackMaker/CallbackMaker.c:625:7: warning: variable ‘menuID’ set but not used [-Wunused-but-set-variable]
   int menuID, subMenuA, subMenuB;
       ^
````

I don't understand the code enough to fix this, but it looks strange:
````
  menuID = glutCreateMenu( MenuCallback );
````
is set but never used after that point, even though it's used by
`glutAddMenuEntry()` calls.

**Comment by dcnieho** [comment]
This variable is indeed not used in the example code, but it is good to show that it exists, as it does hav a use when setting glutSetMenu. Thanks for checking!
