### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by andreasdr** [dcnieho/FreeGLUT#66]
Hi,

I am the author of a 3D engine. Have a look here if interested:
- https://github.com/andreasdr/tdme2

I use FreeGLUT because if supports a lot of Operating Systems. So this is very nice.
But I have some kind of requests. Just telling first.

- I need "DPI awareness" on MacOSX and Windows (GL window is scaled by 2 or something depending on Screen DPI settings, I just would prefer to have to pixels the window has on screen)
- It would be nice to always have the ability to check for control, alt and command keys
- Mousewheel support on FreeBSD does not seem to work, maybe its a problem on their side
- Setting mouse position on MacOSX lacks (I have code that fixes it in my code)
- I have a project cloned here (https://github.com/andreasdr/liquidfun) that has support for iOS, is it possible to merge it

If you would ask for my personal opinion FreeGLUT is nice, but I would drop the utility stuff from FreeGLUT and keep context management and windows creation and input events. Just my opinion in nowadays. Is there still some active development going on or is FreeGLUT dying?

Are you interessted on some kind of collaboration?

I can maybe even help.

Many thanx and

Best regards
Andreas

**Comment by dcnieho** [comment]
Thanks for the interest! The basic principle of freeglut is to stay
backward compatible with old glut, so we don't go nuts with new features or
overhauls. That said, the things you list are within scope of adding as
they either (finally) implement missing functionality, or are optional
things (DPI scaling support) that can be left default off but switched on
by the user. We'd welcome pull requests.
Thanks!

**Comment by dcnieho** [comment]
regarding mouse wheel not working, we have a bug about it:
https://sourceforge.net/p/freeglut/bugs/247/. Here too, pull request welcome

**Comment by andreasdr** [comment]
FreeBSD also added patches some time ago to (update) USB joystick support. Apparently their USB API did change.

Without those patches or no further adjustments the FreeGLUT code does not compile anymore under FreeBSD (11.2).

See here: 
- https://github.com/freebsd/freebsd-ports/tree/master/graphics/freeglut/files

**Comment by dcnieho** [comment]
@andreasdr thanks!
@jtsiomb Are you able to judge this patch?

**Comment by jtsiomb** [comment]
Indeed the freeglut-specific mouse wheel callback extension hase been broken on X11 for some time it seems. On the face of it, this looks reasonable. It looks like if you don't provide a wheel callback it just falls back to the regular button 3 and 4 behavior, which must be maintained for compatibility. I'll try it later to make sure and get back at you.

**Comment by andreasdr** [comment]
Hi,

I also see now that you have no native MacOSX support yet.
Hmm. Is this planned? Or do you like to not have it for some reason?
Just asking.

As GLUT on MacOSX is already deprecated a MacOSX port might be a good point.

Many thanx and

Best regards
Andreas

**Comment by jtsiomb** [comment]
A native MacOS X port would be nice to have. It's just that nobody volunteered to do it. I don't think any of the regular freeglut contributors use MacOS X.

**Comment by rcmaniac25** [comment]
I actually recently picked up one (it was free, and is half falling apart but still works, and I took it to handle random Mac work that I encountered), but I never got around to saying it earlier: macOS/OS X Mojave (latest of of this post) deprecated OpenGL. Sure we can make sure it works on some older Macs, but it's going to eventually die out. Do you put the work in to support something that may eventually never have OpenGL?

**Comment by andreasdr** [comment]
Hmm. Deprecated means not dead. Its just marked deprecated. But sure it might be removed some day. Sorry. Was not aware that it will be deprecated on MacOSX Mojave. 

FreeGLUT is not my project. So its your choice.

I might switch to Metal regarding TDME2 one day but for now I will not put any effort into this.

Btw. I hate that move from Apple since it means more work for me, whereas OpenGL works nice on Windows, FreeBSD, Linux. Apple always was a show stopper here regarding my engine. 
Be it geometry shader related or compute shader related.

**Comment by rcmaniac25** [comment]
I hear you. I don't know others opinions, so I'm not making an decisions for FreeGLUT, just stating the fact.

And it really is a move by Apple to get people to move to Metal. I'd say "instead of moving to Metal, move to Vulkan instead." It works across everything, except Mac, but there are frameworks that wrap Metal to provide a Vulkan API. Since you aren't moving "now", it should have better performance within a year or so. Then you'd be able to support everything.

I'll state that I personally have been playing with adding Vulkan support to FreeGLUT but don't expect anything quick and it's still a question (for me, at least) if that should be a fork of this or (as I've tested it now) a flag that is set, similar to saying one wants GLES vs GL.

But I will wait for others to make an opinion on macOS support (either here or on our mailing list)

**Comment by jtsiomb** [comment]
Apple may be out of touch with reality. But not so much as to remove OpenGL support.

**Comment by andreasdr** [comment]
@rcmaniac25 
Nice one! I was thinking of adding Vulkan too!

I would love to continue to use FreeGLUT with Vulkan if you get this done.
I also heard that it has performance improvements over OpenGL.

@jtsiomb 
I also think they can not drop OpenGL, because I guess there are lots of OpenGL applications on MacOSX used by some one that might event have been initially been done for Unix or such. 
Apple did advertisement when they switched to 64bit which stated something like MacOSX is a perfect match for scientific applications and such. I guess there are some out of them written with OpenGL. Not sure though.

**Comment by andreasdr** [comment]
If I got this right Vulkan also uses GLSL!

**Comment by rcmaniac25** [comment]
@jtsiomb maybe... But the same could be said about the headphone jack and other designs they've done over the years

@andreasdr Vulkan isn't a drop-in replacement. It's a very-low level API to offer near direct access to hardware. That's how it gets its performance. And yes, you can compile GLSL to SPIRV which will run on Vulkan

**Comment by jtsiomb** [comment]
The wheel patch can't be applied by itself. At the very least it needs to come along with a modfiication at the "else" following this. But I have a feeling that the underlying assumption (of this, and the original code) that wheel "buttons" follow after the last mouse button is incorrect, and I want to investigate a bit further first. If the assumption is correct, then fixing the number of buttons query indirectly fixes this problem. Otherwise we need to change the condition to always pass 3 and 4 to the wheel handler (if present), and pass the remaining buttons to the mouse handler.

**Comment by jtsiomb** [comment]
I fixed the wheel callback in SVN revision 1844.

The assumption was incorrect. Wheel buttons are always 4 and 5 (in X11 1-based numbering, 3 and 4 for us), and further mouse buttons continue after that.

glutDeviceGet(GLUT_NUM_MOUSE_BUTTONS) calls XGetPointerMapping, which the manual says will return the number of physical mouse buttons, but in my case it returns 20 while I would expect 9. I don't think this is a big problem, so I won't bother figuring out why it returns such a high count for now.

**Comment by dcnieho** [comment]
Thanks for the discussion and fix guys!

**Comment by andreasdr** [comment]
I do not yet understand the close as e.g. the DPI/Windows question is still open. So I might open another issue with this regard. Also just to mention a MacOSX port would be nice. Maybe I will do this as I need GLUT with DPI awareness on MacOSX.

**Comment by dcnieho** [comment]
Ah, didn't realize by now that more issues were outstanding. Can you
make an issue per issue to keep things organized?

**Comment by jtsiomb** [comment]
Yes, please open one issue for each bug or feature request you want to report. Don't bundle multiple issues in one.
Also my opinion is that the best place to post bug reports is the official bug tracker on sourceforge.
