### ISSUE TITLE
Need help compiling with /MT option in MSVC

### ISSUE THREAD

**Issue by shangjiaxuan** [dcnieho/FreeGLUT#67]
* OS    Windows 10
* FreeGLUT version 3.0.0

I'm trying to compile the source as static library with `/MT` switch on (adding a few lines at the end of `CMakeLists.txt` as referenced [here](https://stackoverflow.com/questions/14172856/cmake-compile-with-mt-instead-of-md) to replace all the command line /MDs with/MT). 

The problem was that when I try to link against the library, I get linker errors and it seems that certain CRT functions were not imported as they were supposed to be (LNK2001 unresolved external symbol __imp___strdup, etc).

Any help on setting things up for compile under /MT? Thanks a lot!

**Comment by Croydon** [comment]
@shangjiaxuan Would you mind explain why you closed this? Did you found a solution?
